name: angular
repository: https://github.com/angulardart-community/angular

packages:
   - "**"
  # - ng_ast
  # - ng_compiler
  # - ng_core
  # - ng_forms
  # - ng_router
  # - ng_test

ignore:
  # - _tests
  - examples
  - tests

command:
  bootstrap:
    usePubspecOverrides: true
