name: angular
repository: https://github.com/angulardart-community/angular

packages:
  - "**"
  # - ngx_ast
  # - ngx_compiler
  # - ngx_dart
  # - ngx_forms
  # - ngx_router
  # - ngx_test

ignore:
  - _tests
  - examples
